<script lang="ts">
    import { i18nStore } from './i18n';
    import Badge from './ui/badge.svelte';

    export let genre: string;
    export let variant: "default" | "secondary" | "destructive" | "outline" = "secondary";

    const genreTranslations: Record<string, Record<string, string>> = {
        en: {
            'Action': 'Action',
            'Adventure': 'Adventure',
            'Animation': 'Animation',
            'Biography': 'Biography',
            'Comedy': 'Comedy',
            'Crime': 'Crime',
            'Documentary': 'Documentary',
            'Drama': 'Drama',
            'Family': 'Family',
            'Fantasy': 'Fantasy',
            'Film-Noir': 'Film-Noir',
            'History': 'History',
            'Horror': 'Horror',
            'Musical': 'Musical',
            'Mystery': 'Mystery',
            'Romance': 'Romance',
            'Sci-Fi': 'Sci-Fi',
            'Sport': 'Sport',
            'Thriller': 'Thriller',
            'War': 'War',
            'Western': 'Western',
            'Art-house': 'Art House',
            'Black-Comedy': 'Black Comedy',
            'Chick-flick': 'Chick Flick',
            'Cult-classic': 'Cult Classic',
            'Dark-Comedy': 'Dark Comedy',
            'Epic': 'Epic',
            'Erotic': 'Erotic',
            'Experimental': 'Experimental',
            'Fairy-tale': 'Fairy Tale',
            'Film-within-a-film': 'Film Within a Film',
            'Futuristic': 'Futuristic',
            'Gangster': 'Gangster',
            'Heist': 'Heist',
            'Historical': 'Historical',
            'Holiday': 'Holiday',
            'Indie': 'Indie',
            'Juvenile': 'Juvenile',
            'Melodrama': 'Melodrama',
            'Monster': 'Monster',
            'Political': 'Political',
            'Psychological': 'Psychological',
            'Road-movie': 'Road Movie',
            'Satire': 'Satire',
            'Science-Fiction': 'Science Fiction',
            'Slapstick': 'Slapstick',
            'Social-issue': 'Social Issue',
            'Superhero': 'Superhero',
            'Surreal': 'Surreal',
            'Teen': 'Teen',
            'Vampire': 'Vampire',
            'Zombie': 'Zombie'
        },
        es: {
            'Action': 'Acción',
            'Adventure': 'Aventura',
            'Animation': 'Animación',
            'Biography': 'Biografía',
            'Comedy': 'Comedia',
            'Crime': 'Crimen',
            'Documentary': 'Documental',
            'Drama': 'Drama',
            'Family': 'Familiar',
            'Fantasy': 'Fantasía',
            'Film-Noir': 'Cine Negro',
            'History': 'Historia',
            'Horror': 'Terror',
            'Musical': 'Musical',
            'Mystery': 'Misterio',
            'Romance': 'Romance',
            'Sci-Fi': 'Ciencia Ficción',
            'Sport': 'Deporte',
            'Thriller': 'Suspense',
            'War': 'Guerra',
            'Western': 'Oeste',
            'Art-house': 'Cine de Arte',
            'Black-Comedy': 'Comedia Negra',
            'Chick-flick': 'Película para Chicas',
            'Cult-classic': 'Clásico de Culto',
            'Dark-Comedy': 'Comedia Oscura',
            'Epic': 'Épico',
            'Erotic': 'Erótico',
            'Experimental': 'Experimental',
            'Fairy-tale': 'Cuento de Hadas',
            'Film-within-a-film': 'Película dentro de Película',
            'Futuristic': 'Futurista',
            'Gangster': 'Gángster',
            'Heist': 'Atraco',
            'Historical': 'Histórico',
            'Holiday': 'Vacaciones',
            'Indie': 'Independiente',
            'Juvenile': 'Juvenil',
            'Melodrama': 'Melodrama',
            'Monster': 'Monstruos',
            'Political': 'Político',
            'Psychological': 'Psicológico',
            'Road-movie': 'Película de Carretera',
            'Satire': 'Sátira',
            'Science-Fiction': 'Ciencia Ficción',
            'Slapstick': 'Comedia Física',
            'Social-issue': 'Problema Social',
            'Superhero': 'Superhéroe',
            'Surreal': 'Surrealista',
            'Teen': 'Adolescente',
            'Vampire': 'Vampiros',
            'Zombie': 'Zombis'
        },
        fr: {
            'Action': 'Action',
            'Adventure': 'Aventure',
            'Animation': 'Animation',
            'Biography': 'Biographie',
            'Comedy': 'Comédie',
            'Crime': 'Crime',
            'Documentary': 'Documentaire',
            'Drama': 'Drame',
            'Family': 'Famille',
            'Fantasy': 'Fantaisie',
            'Film-Noir': 'Film Noir',
            'History': 'Histoire',
            'Horror': 'Horreur',
            'Musical': 'Musical',
            'Mystery': 'Mystère',
            'Romance': 'Romance',
            'Sci-Fi': 'Science-Fiction',
            'Sport': 'Sport',
            'Thriller': 'Thriller',
            'War': 'Guerre',
            'Western': 'Western',
            'Art-house': 'Film d\'Art',
            'Black-Comedy': 'Comédie Noire',
            'Chick-flick': 'Film pour Filles',
            'Cult-classic': 'Film Culte',
            'Dark-Comedy': 'Comédie Sombre',
            'Epic': 'Épique',
            'Erotic': 'Érotique',
            'Experimental': 'Expérimental',
            'Fairy-tale': 'Conte de Fées',
            'Film-within-a-film': 'Film dans un Film',
            'Futuristic': 'Futuriste',
            'Gangster': 'Gangster',
            'Heist': 'Braquage',
            'Historical': 'Historique',
            'Holiday': 'Vacances',
            'Indie': 'Indépendant',
            'Juvenile': 'Jeunesse',
            'Melodrama': 'Mélodrame',
            'Monster': 'Monstre',
            'Political': 'Politique',
            'Psychological': 'Psychologique',
            'Road-movie': 'Film de Route',
            'Satire': 'Satire',
            'Science-Fiction': 'Science-Fiction',
            'Slapstick': 'Burlesque',
            'Social-issue': 'Problème Social',
            'Superhero': 'Super-héros',
            'Surreal': 'Surréaliste',
            'Teen': 'Adolescent',
            'Vampire': 'Vampire',
            'Zombie': 'Zombie'
        },
        de: {
            'Action': 'Action',
            'Adventure': 'Abenteuer',
            'Animation': 'Animation',
            'Biography': 'Biografie',
            'Comedy': 'Komödie',
            'Crime': 'Krimi',
            'Documentary': 'Dokumentation',
            'Drama': 'Drama',
            'Family': 'Familie',
            'Fantasy': 'Fantasy',
            'Film-Noir': 'Film Noir',
            'History': 'Geschichte',
            'Horror': 'Horror',
            'Musical': 'Musical',
            'Mystery': 'Mystery',
            'Romance': 'Romanze',
            'Sci-Fi': 'Science-Fiction',
            'Sport': 'Sport',
            'Thriller': 'Thriller',
            'War': 'Krieg',
            'Western': 'Western',
            'Art-house': 'Kunstfilm',
            'Black-Comedy': 'Schwarze Komödie',
            'Chick-flick': 'Frauenfilm',
            'Cult-classic': 'Kultfilm',
            'Dark-Comedy': 'Schwarzer Humor',
            'Epic': 'Epos',
            'Erotic': 'Erotik',
            'Experimental': 'Experimentell',
            'Fairy-tale': 'Märchen',
            'Film-within-a-film': 'Film im Film',
            'Futuristic': 'Futuristisch',
            'Gangster': 'Gangster',
            'Heist': 'Heist',
            'Historical': 'Historisch',
            'Holiday': 'Urlaub',
            'Indie': 'Independent',
            'Juvenile': 'Jugend',
            'Melodrama': 'Melodrama',
            'Monster': 'Monster',
            'Political': 'Politisch',
            'Psychological': 'Psychologisch',
            'Road-movie': 'Roadmovie',
            'Satire': 'Satire',
            'Science-Fiction': 'Science-Fiction',
            'Slapstick': 'Slapstick',
            'Social-issue': 'Soziales Drama',
            'Superhero': 'Superheld',
            'Surreal': 'Surreal',
            'Teen': 'Teenager',
            'Vampire': 'Vampir',
            'Zombie': 'Zombie'
        }
    };

    $: translatedGenre = genreTranslations[$i18nStore.language]?.[genre] || genre;
</script>

<Badge {variant}>
    {translatedGenre}
</Badge> 